name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up PHP and necessary extensions
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, sqlite3, bcmath, intl, gd

    # Install dependencies
    - name: Install Composer dependencies
      run: |
        composer install --no-interaction --prefer-dist

    # Create SQLite Database File
    - name: Create SQLite Database File
      run: |
        touch database/database.sqlite

    # Set up environment variables
    - name: Set up .env
      run: |
        cp .env.example .env
        php artisan key:generate

    # Run Database Migrations
    - name: Run Database Migrations
      run: php artisan migrate --force

    # Run Tests
    - name: Run PHPUnit Tests
      run: vendor/bin/phpunit --configuration phpunit.xml

    # Optionally, you can cache dependencies to speed up future runs
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
