name: PHP PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Install dependencies
      run: |
        composer install --no-interaction

    - name: Set up .env file
      run: |
        cp .env.example .env  # Copy the example .env to .env
        echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env  # Add the APP_KEY to .env

    - name: Run PHPUnit tests
      run: |
        vendor/bin/phpunit --configuration phpunit.xml

    - name: Cache PHPUnit and Composer dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.composer/cache
          vendor/
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
