name: PHP PHPUnit Tests

on:
  push:
    branches:
      - main  # Trigger on push to main (or your default branch)
  pull_request:
    branches:
      - main  # Trigger on pull request to main (or your default branch)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'  # Use the PHP version you're working with

    - name: Install dependencies
      run: |
        composer install --no-interaction

    - name: Run PHPUnit tests
      run: |
        vendor/bin/phpunit --configuration phpunit.xml
      continue-on-error: false # Ensure the workflow stops on test failure

    - name: Cache PHPUnit and Composer dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.composer/cache
          vendor/
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Clear cache if necessary
      run: |
        rm -rf vendor/
        composer install --no-interaction

    - name: Re-run PHPUnit tests after clearing cache
      run: |
        vendor/bin/phpunit --configuration phpunit.xml
